### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/persistence/JoinColumn

### ISSUE THREAD

**Issue by walfud** [baoyongzhang/ParcelableGenerator#18]
我们在项目中使用 PG, 倍感方便之余, 也遇到了一些麻烦. 当我们使用 `@com.baoyz.pg.Parcelable` 修饰一个类的时候, 

``` java
/**
 * Created by walfud on 2015/8/7.
 */
@com.baoyz.pg.Parcelable
public class ParcelableUser extends User {
    public ParcelableUser() {
    }

    public ParcelableUser(User user) {
        super();
//        super.copyFrom(user);
        setId(user.getId());
        setMobile(user.getMobile());
        setPwd(user.getPwd());
        setImei(user.getImei());
        setName(user.getName());
        setNickname(user.getNickname());
        setBirthdate(user.getBirthdate());
        setGender(user.getGender());
        setQq(user.getQq());
        setWechat(user.getWechat());
        setEmail(user.getEmail());
        setCompany(user.getCompany());
        setCompany_addr(user.getCompany_addr());
        setHome_addr(user.getHome_addr());
        setRegtime(user.getRegtime());
        setMood(user.getMood());
        setStatus(user.getStatus());
    }
}
```

在 `startActivity` 时发生了崩溃, 信息如下:

```
09-06 08:50:08.302  20435-20435/walfud.meetu E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: javax/persistence/JoinColumn
            at java.lang.reflect.Field.isAnnotationPresent(Native Method)
            at java.lang.reflect.Field.isAnnotationPresent(Field.java:221)
            at com.baoyz.pg.PGUtils.checkSerializable(PGUtils.java:85)
            at com.baoyz.pg.PGUtils.writeValue(PGUtils.java:55)
            at com.baoyz.pg.PGUtils.write(PGUtils.java:45)
            at com.baoyz.pg.PGUtils.write(PGUtils.java:49)
            at com.baoyz.pg.PGUtils.write(PGUtils.java:38)
```

我写了一个 demo (https://github.com/walfud/MyApplication.git) 供你查看.
希望能得到你的帮助, 以便我们今后继续使用 PG.

感谢.

**Comment by baoyongzhang** [comment]
好的，我看一下

**Comment by walfud** [comment]
感谢帮助. 我等你结果~

**Comment by baoyongzhang** [comment]
你不用PG就不会报错么？JoinColum这个Class找不到，这个和PG并没有关系，JoinColumn这个类Android里面应该是没有的。

**Comment by baoyongzhang** [comment]
然而我跑你这个Demo并没有报错

**Comment by walfud** [comment]
想必你测试用的是 5.+ 的系统吧? 我发现我的 4.2.2 (genymotion) 会崩溃, 但是 5.1.1 就没事儿. 这应该是 系统 jre 的问题?

**Comment by walfud** [comment]
好吧, 总之应该跟 PG 没关系, 我们再想想办法. 感谢 Mr.Bao
